export const WEBSOCKET_OPENED = 'WEBSOCKET_OPENED';
export const WEBSOCKET_CLOSED = 'WEBSOCKET_CLOSED';
export const WEBSOCKET_MESSAGE_RECEIVED = 'WEBSOCKET_MESSAGE_RECEIVED';
export const WEBSOCKET_ERROR_THROWN = 'WEBSOCKET_ERROR_THROWN';
